# Generated by Django 3.1.4 on 2020-12-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstName',
            new_name='name',
        ),
    ]
